WIP: Pipeline compiler should not alter specifyed image
woodpecker-ci/woodpecker pull request #1005
Opened 2022-07-02 13:52 UTC by 6543

adress #1003

# this is not jet tested at all

2022-08-25 13:13 UTC, 6543 commented
let's wait ~1-2days and if no errors get reported it's fine

2022-08-25 16:36 UTC, thestr4ng3r requested changes
You will still need to remove the workaround here, which was added for the old behavior:
```diff
diff --git a/pipeline/backend/local/local.go b/pipeline/backend/local/local.go
index e1215a00..cc636fb9 100644
--- a/pipeline/backend/local/local.go
+++ b/pipeline/backend/local/local.go
@@ -62,7 +62,7 @@ func (e *local) Exec(ctx context.Context, proc *types.Step) error {
                Command = append(Command, "plugin-git")
        } else {
                // Use "image name" as run command
-               Command = append(Command, proc.Image[18:len(proc.Image)-7])
+               Command = append(Command, proc.Image)
                Command = append(Command, "-c")

                // Decode script and delete initial lines
```

Otherwise this happens:
```
panic: runtime error: slice bounds out of range [18:2]

goroutine 44 [running]:
github.com/woodpecker-ci/woodpecker/pipeline/backend/local.(*local).Exec(0x1400026b920, {0x1011d0758?, 0x14000596940}, 0x140005dcd20)
	/Users/florian/dev/woodpecker/pipeline/backend/local/local.go:65 +0x8a0
github.com/woodpecker-ci/woodpecker/pipeline.(*Runtime).exec(0x1400052c070, 0x140005dcd20)
	/Users/florian/dev/woodpecker/pipeline/pipeline.go:216 +0x140
github.com/woodpecker-ci/woodpecker/pipeline.(*Runtime).execAll.func1()
	/Users/florian/dev/woodpecker/pipeline/pipeline.go:181 +0x1b8
golang.org/x/sync/errgroup.(*Group).Go.func1()
	/Users/florian/go/pkg/mod/golang.org/x/sync@v0.0.0-20220819030929-7fc1605a5dde/errgroup/errgroup.go:75 +0x5c
created by golang.org/x/sync/errgroup.(*Group).Go
	/Users/florian/go/pkg/mod/golang.org/x/sync@v0.0.0-20220819030929-7fc1605a5dde/errgroup/errgroup.go:72 +0xa4
```

If the slicing is removed, the changes work for my use-cases.

2022-08-26 06:58 UTC, thestr4ng3r approved these changes

2022-08-26 18:00 UTC, merged

2022-08-27 08:09 UTC, thestr4ng3r commented
Thanks a lot!