Renamed procs to steps in code #1288
woodpecker-ci/woodpecker pull request #1331
Opened 2022-10-24 11:48 UTC by Harikesh00

Renamed `procs` to `steps` in code #1288

2022-10-24 11:54 UTC, Harikesh00 commented
@6543 plz review

2022-10-24 14:53 UTC, 6543 requested changes

2022-10-24 14:53 UTC, 6543 commented on cmd/agent/flags.go
> +		EnvVars: []string{"WOODPECKER_MAX_STEPS"},
```suggestion
		EnvVars: []string{"WOODPECKER_MAX_STEPS", "WOODPECKER_MAX_PROCS"},
```

2022-10-24 14:53 UTC, 6543 commented on server/model/log.go
> +	StepID int64  `xorm:"UNIQUE 'log_job_id'"`
```suggestion
	StepID int64  `xorm:"UNIQUE 'log_step_id'"`
```
+migration

2022-10-24 16:55 UTC, Harikesh00 commented on agent/runner.go
> +			Step: step.Alias,
reverting

2022-10-24 16:56 UTC, Harikesh00 commented on agent/runner.go
> +			Step:     state.Pipeline.Step.Alias,
reverting

2022-10-24 16:56 UTC, Harikesh00 commented on cli/exec/line.go
> +	Step string `json:"step,omitempty"`
reverting

2022-10-24 17:07 UTC, Harikesh00 commented on cli/pipeline/ps.go
> +	for _, step := range pipeline.Steps {
reverting

2022-10-24 17:19 UTC, Harikesh00 commented on docs/versioned_docs/version-0.15/30-administration/00-setup.md
>  >
reverted

2022-10-24 17:21 UTC, Harikesh00 commented on pipeline/backend/local/local.go
> +func (e *local) Setup(ctx context.Context, step *types.Config) error {
done

2022-10-24 17:22 UTC, Harikesh00 commented on pipeline/backend/ssh/ssh.go
> +func (e *ssh) Setup(ctx context.Context, step *types.Config) error {
done

2022-10-24 17:24 UTC, Harikesh00 commented on pipeline/rpc/line.go
> +	Step string `json:"step,omitempty"`
?
didn't get u

2022-10-24 17:24 UTC, Harikesh00 commented on pipeline/tracer.go
> +// Trace calls f(step, state).
done

2022-10-24 17:26 UTC, Harikesh00 commented on server/model/file.go
> +	StepID     int64  `json:"step_id" xorm:"UNIQUE(s) INDEX 'file_step_id'"`
should I revert this change 
or can I write a migration script?
if yes any reference for it, from where I can follow

2022-10-24 17:39 UTC, Harikesh00 commented on server/store/datastore/migration/000_legacy_to_xorm.go
> -			// procs
reverted

2022-10-24 17:39 UTC, Harikesh00 commented on server/store/datastore/migration/000_legacy_to_xorm.go
> +				"DROP INDEX IF EXISTS file_step_ix;",
reverted

2022-10-24 19:41 UTC, 6543 commented on cli/pipeline/ps.go
> +	for _, step := range pipeline.Steps {
well you can do it in this batch but then you need migrations

2022-10-25 05:19 UTC, Harikesh00 commented on cli/pipeline/ps.go
> +	for _, step := range pipeline.Steps {
ok, I'll write the migration
can I get any reference for it?
from where I can follow what all changes need to do & make the changes

2022-10-25 08:01 UTC, 6543 commented on cli/pipeline/ps.go
> +	for _, step := range pipeline.Steps {
https://github.com/woodpecker-ci/woodpecker/pull/1296

2022-10-25 10:51 UTC, 6543 commented on docs/versioned_docs/version-0.15/30-administration/00-setup.md
>  >
@Harikesh00 pull did not get new commits, did you forgot to push?

2022-10-25 11:01 UTC, Harikesh00 commented on docs/versioned_docs/version-0.15/30-administration/00-setup.md
>  >
haven't pushed yet
waiting for confirmation on migration changes.
do I cover migration changes in the same MR
or should I revert the migration changes & will cover in next MR?

2022-10-25 11:07 UTC, 6543 commented on docs/versioned_docs/version-0.15/30-administration/00-setup.md
>  >
well just do it in here ... dont force push just append commits, we squashmerge

2022-10-25 11:09 UTC, 6543 commented on server/model/file.go
> +	StepID     int64  `json:"step_id" xorm:"UNIQUE(s) INDEX 'file_step_id'"`
https://github.com/woodpecker-ci/woodpecker/blob/master/CONTRIBUTING.md#code-review

2022-10-25 11:09 UTC, 6543 commented on server/model/file.go
> +	StepID     int64  `json:"step_id" xorm:"UNIQUE(s) INDEX 'file_step_id'"`
just migrate

2022-10-26 03:06 UTC, Harikesh00 commented on docs/versioned_docs/version-0.15/30-administration/00-setup.md
>  >
ok sure
I'll inform here once changes push

2022-10-26 05:18 UTC, Harikesh00 commented
@6543 @qwerty287  all breaking changes that are commented on PR are because of migration?
if I add the migration script then can I keep those changes? (no need to revert)

2022-10-26 05:38 UTC, Harikesh00 commented on server/model/file.go
> +	StepID     int64  `json:"step_id" xorm:"UNIQUE(s) INDEX 'file_step_id'"`
ok

2022-10-26 17:25 UTC, Harikesh00 commented on cmd/agent/flags.go
> +		EnvVars: []string{"WOODPECKER_MAX_STEPS"},
done

2022-10-26 17:27 UTC, Harikesh00 commented
@qwerty287 @6543 migration script added & review comments resolved
plz review

2022-10-26 17:29 UTC, Harikesh00 commented
I didn't get what fallback means, why it's required and what it will do
can u plz explain

2022-10-27 00:47 UTC, 6543 commented on cmd/agent/flags.go
> +		EnvVars: []string{"WOODPECKER_MAX_STEPS", "WOODPECKER_MAX_PROCS"},
well still that's not steps but workflows ...

2022-10-27 15:27 UTC, 6543 commented on agent/runner.go
> +	// get the next pipeline from the queue
```suggestion
	// get the next workflow from the queue
```

2022-10-27 15:30 UTC, 6543 commented on cli/exec/flags.go
> +		EnvVars: []string{"CI_STEP_NUMBER"},
```suggestion
		EnvVars: []string{"CI_STEP_NUMBER", "CI_JOB_NUMBER"},
```

2022-10-27 15:32 UTC, 6543 commented on docs/docs/30-administration/00-setup.md
> +> You can add more agents to increase the number of parallel steps or set the agent's `WOODPECKER_MAX_WORKFLOWS=1` environment variable to increase the number of parallel builds for that agent.
```suggestion
> You can add more agents to increase the number of parallel steps or set the agent's `WOODPECKER_MAX_WORKFLOWS=1` environment variable to increase the number of parallel workflows for that agent.
```

2022-10-27 15:33 UTC, 6543 commented on docs/docs/92-awesome.md
> +- [picus](https://github.com/windsource/picus) - Picus connects to a Woodpecker CI server and creates an agent in the cloud when there are pending steps.
```suggestion
- [picus](https://github.com/windsource/picus) - Picus connects to a Woodpecker CI server and creates an agent in the cloud when there are pending workflows.
```

2022-10-27 15:39 UTC, 6543 commented on pipeline/tracer.go
> +	state.Pipeline.Step.Environment["CI_STEP_STARTED"] = strconv.FormatInt(state.Pipeline.Time, 10)
can we sort all deprecated blocks below ?

2022-10-27 15:48 UTC, 6543 commented on server/store/datastore/migration/011_columns_rename_procs_to_steps.go
> +var renameTableProcsToSteps = task{
could you put them into one migration func ... why do we need different one?

2022-10-27 16:54 UTC, 6543 commented on cmd/agent/flags.go
> +		Name:    "max-steps",
```suggestion
		Name:    "max-workflows",
```

2022-10-27 16:58 UTC, 6543 commented
diff --git a/web/components.d.ts b/web/components.d.ts
index 8a53c720..0600280b 100644
--- a/web/components.d.ts
+++ b/web/components.d.ts
@@ -75,8 +75,6 @@ declare module '@vue/runtime-core' {
     PipelineItem: typeof import('./src/components/repo/pipeline/PipelineItem.vue')['default']
     PipelineList: typeof import('./src/components/repo/pipeline/PipelineList.vue')['default']
     PipelineLog: typeof import('./src/components/repo/pipeline/PipelineLog.vue')['default']
-    PipelineProcDuration: typeof import('./src/components/repo/pipeline/PipelineProcDuration.vue')['default']
-    PipelineProcList: typeof import('./src/components/repo/pipeline/PipelineProcList.vue')['default']
     PipelineRunningIcon: typeof import('./src/components/repo/pipeline/PipelineRunningIcon.vue')['default']
     PipelineStatusIcon: typeof import('./src/components/repo/pipeline/PipelineStatusIcon.vue')['default']
     PipelineStepDuration: typeof import('./src/components/repo/pipeline/PipelineStepDuration.vue')['default']

2022-10-28 13:42 UTC, 6543 commented on server/shared/stepStatus.go
> +// Copyright 2019 mhmxs.
```suggestion
// Copyright 2022 Woodpecker Authors
// Copyright 2019 mhmxs
```

2022-10-28 13:43 UTC, 6543 commented on server/shared/stepStatus_test.go
> +// Copyright 2019 mhmxs.
```suggestion
// Copyright 2022 Woodpecker Authors
// Copyright 2019 mhmxs
```

2022-10-28 13:43 UTC, 6543 approved these changes

2022-10-28 15:38 UTC, merged

2022-10-29 12:16 UTC, 6543 commented
:point_up:

2022-11-02 17:44 UTC, Harikesh00 commented
Thank you @6543 @qwerty287 for all your support, you did a lot