Fully support `.yaml`
woodpecker-ci/woodpecker pull request #1713
Opened 2023-04-22 08:04 UTC by qwerty287

Follow-up to https://github.com/woodpecker-ci/woodpecker/pull/1388
Closes https://github.com/woodpecker-ci/woodpecker/issues/1073

2023-04-22 18:16 UTC, 6543 requested changes
I acknowledge the consensus, that we should support yaml too ...

But I dont see why we should do a breaking change in the order and make yaml default over yml ?!?

2023-04-22 19:50 UTC, 6543 commented
@anbraten your opinion?

2023-04-24 12:10 UTC, lafriks commented
> I acknowledge the consensus, that we should support yaml too ...
> 
> But I dont see why we should do a breaking change in the order and make yaml default over yml ?!?

I don't think it's being breaking for many as there is already something very wrong if you have both `.woodpecker.yml` and `.woodpecker.yaml` in project

2023-04-29 03:43 UTC, 6543 approved these changes

2023-04-29 08:12 UTC, merged