Manually skip workflow and its depending ones
woodpecker-ci/woodpecker pull request #1731
Opened 2023-05-01 08:40 UTC by qwerty287

Supersedes #1463 
Closes #1354

2023-05-01 17:35 UTC, anbraten requested changes
Could you explain your use-case again. One issue I see with allowing such things is that you could bypass the CI. Especially if working in Teams this is a real issue as admins / users could skip workflows needed to ensure quality without editing the config and therefore without sticking to flows like reviews. For example in the Woodpecker project this way a maintainer could easily bypass a check without fixing the real issue.

2023-05-31 16:38 UTC, 6543 commented
well only repo admins should be allowed to skip workflows ... and normal users with rite acces should just be able to cancle ...

2023-05-31 16:38 UTC, 6543 commented
or we just report cancled and all is fine?

2023-06-03 02:20 UTC, 6543 commented on server/pipeline/pipelineStatus.go
> +func UpdateToStatusSkipped(store model.UpdatePipelineStore, pipeline model.Pipeline, reviewer string) (*model.Pipeline, error) {
never used?

2023-06-03 02:21 UTC, 6543 commented on server/queue/queue.go
> +	EvictCurrent(c context.Context, id string, exitStatus model.StatusValue) error
please add code comment of what it does here too :)

2023-06-05 14:15 UTC, 6543 commented
Well lets just mae it a server config option and let id be disabled by default

2023-06-05 14:56 UTC, 6543 commented
well it depends if the cancel let depending pipelines will going to run or if they are sciped

2023-06-05 14:56 UTC, lafriks commented
Question is if part of the pipeline is skipped and when it finishes does whole pipeline status remains as canceled or success?

2023-06-05 14:57 UTC, 6543 commented on server/api/pipeline.go
> +//	@Summary	Skip a workflow
```suggestion
//	@Summary	Skip a workflow and it's depending ones
```

2023-06-05 15:26 UTC, 6543 approved these changes

2023-06-05 15:35 UTC, 6543 commented
also tested - works as proposed

2023-06-05 15:56 UTC, lafriks requested changes

2023-06-05 15:56 UTC, lafriks commented on server/model/step.go
> +	return p.State == StatusError || p.State == StatusKilled || p.State == StatusFailure || p.State == StatusSkipped
Wouldn't this also make skipped by condition pipelines mark as failed?

2023-06-11 01:09 UTC, 6543 commented
ok what's the current review proccess of you?
cc @anbraten @lafriks

2023-07-02 16:12 UTC, 6543 requested changes

2023-07-02 16:12 UTC, 6543 commented on server/store/datastore/workflow.go
> +	return wf, wrapGet(s.engine.Get(wf))
explizite when statement instead of implizite query

2023-07-02 16:12 UTC, 6543 commented on server/store/datastore/workflow.go
> +	return wf, wrapGet(s.engine.Get(wf))
and tests for that feature

2023-08-02 07:41 UTC, anbraten commented
I am still unsure how we can prevent pipeline bypassing after adding this feature. In case of Github we would have to define all required status-checks (which for example in the woodpecker projects we are not atm). However that would be possible, but in case of Bitbucket and Gitlab we don't have such options:
![image](https://github.com/woodpecker-ci/woodpecker/assets/6918444/7b56e5c6-5924-4566-b240-3079b0c605b4)

Sending a failed status-check in case of skipping a workflow, would be solving this, but I guess that would not help with the intention of this PR.

2023-08-02 07:55 UTC, anbraten commented
Currently it creates pending status-checks for all workflows after pushing. To merge the PR there has to be at least one status-check so you can not bypass even if Woodpecker would be offline etc. If I currently cancel a complete pipeline it is marked as failed and therefore it prevents the merge.

2023-08-02 09:38 UTC, anbraten commented
Could we maybe add an `optional` setting to workflows which would allow skipping a workflow and normally it would not be allowed to skip any workflows?

2023-08-02 10:52 UTC, anbraten commented
> Ah, I see. You're right, sending failed status would solve it, but that's not the idea. I think it's fine though to send a failed status for every skipped pipeline (which would also include pipelines that didn't start when canceling). What do you think about this?

Sending failed status for skipped workflows would be fine for the security aspect. Could you explain how you plan to use the skipping of workflows then? 

So for example with Woodpecker you would start a pipeline by opening a PR. You wait for the tests, but the docs and UI workflows you don't care about and would skip it. Push changes to the go code until you have finished it and at the end you would run all workflows to be able to merge?

2023-08-02 11:05 UTC, closed without merging