Add own workflow model
woodpecker-ci/woodpecker pull request #1784
Opened 2023-05-29 15:14 UTC by qwerty287

Closes #1287

2023-05-30 19:25 UTC, anbraten commented
Maybe related to https://github.com/woodpecker-ci/woodpecker/blob/master/server/store/datastore/migration/migration_test.go#L94

2023-06-06 10:10 UTC, 6543 commented on server/grpc/rpc.go
> +	if model.IsMultiPipeline(currentPipeline.Workflows) {
I think we now can move the IsMultiPipeline func as func of the pipeline model

2023-06-06 10:10 UTC, 6543 commented on server/model/pipeline.go
> +	Workflows           []*Workflow       `json:"workflows,omitempty"         xorm:"-"`
fmt

2023-06-06 10:16 UTC, 6543 commented on server/store/store.go
> +	StepListWorkflow(*model.Workflow) ([]*model.Step, error)
```suggestion
	StepListFromWorkflow(*model.Workflow) ([]*model.Step, error)
```
?

2023-06-06 12:09 UTC, anbraten commented on server/store/store.go
> +	StepListFromWorkflow(*model.Workflow) ([]*model.Step, error)
Could be helpful to call it `StepListFromWorkflowFind` or `StepListFromWorkflowGet` etc to know that its not setting, but getting data.

2023-06-06 12:09 UTC, anbraten commented on server/store/store.go
> +	WorkflowTree(*model.Pipeline) ([]*model.Workflow, error)
Same for this one. Maybe `WorkflowGetTree`

2023-06-06 13:52 UTC, 6543 commented on server/model/step.go
> +	PGID       int         `json:"pgid"                 xorm:"step_pgid"`
well i "guess" it's the `group`  setting that manage concurent step runs ... but I'm not certain as I would have to look that up in code

2023-06-07 12:02 UTC, 6543 commented on server/model/step.go
> +	PGID       int         `json:"pgid"                 xorm:"step_pgid"`
oh so we can drop it :)

2023-06-10 16:15 UTC, 6543 commented on server/forge/common/status.go
> +		"pipeline": workflow.Name,
hmm we should rename pipeline

2023-06-10 16:15 UTC, 6543 commented on server/forge/common/status.go
> +		"pipeline": workflow.Name,
PS: and also not forget to change the docs acordingly

2023-06-10 16:18 UTC, 6543 commented on server/grpc/rpc.go
> -	s.updateForgeStatus(c, repo, currentPipeline, step)
is updateForgeStatus not needed here anymore ?!?

2023-06-10 16:44 UTC, 6543 commented on server/pipeline/helper.go
> +	for _, step := range pipeline.Workflows {
```suggestion
	for _, workflow := range pipeline.Workflows {
```

2023-06-10 16:44 UTC, 6543 commented on server/pipeline/helper.go
>  		err := server.Config.Services.Forge.Status(ctx, user, repo, pipeline, step)
```suggestion
		err := server.Config.Services.Forge.Status(ctx, user, repo, pipeline, workflow)
```

2023-06-10 16:44 UTC, 6543 commented on server/pipeline/start.go
> +			for _, step := range steps {
```suggestion
			for _, step := range wf.Children {
```

2023-06-10 16:44 UTC, 6543 commented on server/store/datastore/workflow.go
> +func (s storage) WorkflowGetTree(pipeline *model.Pipeline) ([]*model.Workflow, error) {
we need tests for this functions :D

2023-06-10 16:44 UTC, 6543 commented on web/src/lib/api/types/pipeline.ts
> +  exit_code: number;
```suggestion
```

2023-06-10 16:54 UTC, 6543 commented on server/pipeline/cancel.go
> +				log.Error().Msgf("error: done: cannot update step_id %d state: %s", workflow.ID, err)
```suggestion
				log.Error().Msgf("cannot update workflow with id %d state: %s", workflow.ID, err)
```

2023-06-10 16:55 UTC, 6543 commented on server/pipeline/cancel.go
> +					log.Error().Msgf("error: done: cannot update step_id %d state: %s", workflow.ID, err)
```suggestion
					log.Error().Err(err).Msgf("cannot update workflow with id %d state", workflow.ID)
```

2023-06-10 16:59 UTC, 6543 commented on server/store/datastore/step.go
>  	if err := sess.Begin(); err != nil {
session begin part should be at session opener

2023-06-10 21:49 UTC, 6543 requested changes
view logs do not work anymore and you can not cancel cron jobs ?!?

2023-06-19 16:16 UTC, 6543 commented
well in master there did land some bugfixes that could address that ...

I'm just waiting for https://github.com/woodpecker-ci/woodpecker/pull/1784#discussion_r1225457801 to be addressed @qwerty287 

after that I'll retest :)

2023-06-19 16:20 UTC, 6543 commented
@qwerty287 updated to latest maister

2023-06-19 18:32 UTC, 6543 commented on server/store/datastore/workflow.go
> +	if err := sess.Begin(); err != nil {
why was the defer session close removed?

2023-06-19 18:34 UTC, 6543 commented on server/store/datastore/migration/019_parent_steps_to_workflows.go
> +//
it's 020_ now ...

2023-06-20 12:27 UTC, lafriks commented on server/forge/gitea/gitea_test.go
```suggestion
```

2023-06-27 09:13 UTC, pat-s commented
Does this need more testing or is it ready to merge? Can't quite infer it from the last comments.

@qwerty287 I guess you've tested this already on your instance?

2023-06-27 16:01 UTC, merged

2023-06-27 17:07 UTC, 6543 commented
af20d2b445a1ff32db49913d6455cd9ffc738db0 and 3e0bb3dd5613346171609b2a55911a7fe5a5fb53 fixed my issues ... just did not had time to test it again