Fix UI and backend paths with subpath
woodpecker-ci/woodpecker pull request #1799
Opened 2023-06-01 11:06 UTC by qwerty287

I'm not sure if this is an ideal fix for this, but it seems to work for me. If you have another idea just let me know.

Closes #1798 
Closes #1773

2023-06-01 23:05 UTC, liyimeng commented on web/src/router.ts
> +if (rootURL !== '' && rootURL !== null) {
Using  '??' to chech  rootURL can be more robust?

2023-06-02 05:20 UTC, Seryta commented
Some links in js still have no rooturl, and this pr still doesn't solve the problem for me.
![image](https://github.com/woodpecker-ci/woodpecker/assets/31036794/23dd25f7-4b33-4e3e-99f3-0e921a12a812)

2023-06-02 05:52 UTC, Seryta commented
> Can you give the exact issues? Were are links that do not work for you?

https://github.com/woodpecker-ci/woodpecker/issues/1798#issuecomment-1573191668

2023-06-02 06:42 UTC, Seryta commented
> @Seryta I tried fixing them in [0ce8f1f](https://github.com/woodpecker-ci/woodpecker/commit/0ce8f1fde805cd8f6a516aa62eb00b3ec923cad8). It's possible that I missed something, can you test again?

this is the latest situation: https://github.com/woodpecker-ci/woodpecker/issues/1798#issuecomment-1573233074

2023-06-02 06:50 UTC, Seryta commented
> Are there any errors in the browser/JS console?

Oh, yes, the error is as follows:
![image](https://github.com/woodpecker-ci/woodpecker/assets/31036794/852bc195-cc8c-4f1b-9c10-8912caaa3834)

![image](https://github.com/woodpecker-ci/woodpecker/assets/31036794/2b5c1f52-4a45-4202-9eb5-b9ea23da784b)

2023-06-02 07:04 UTC, Seryta commented
There may also be a problem with another file, web/src/lib/api/index.ts

https://github.com/woodpecker-ci/woodpecker/blob/71d7a467f904eb83432227450693f1b66b6075dd/web/src/lib/api/index.ts#L290

https://github.com/woodpecker-ci/woodpecker/blob/71d7a467f904eb83432227450693f1b66b6075dd/web/src/lib/api/index.ts#L303

2023-06-02 07:39 UTC, Seryta commented
> Can you try again with [75ef337](https://github.com/woodpecker-ci/woodpecker/pull/1799/commits/75ef3372d8bca23f88c7b8e815f7d66b7c9063c9)?

Now the content can be displayed, but as I said above, there is a problem with `/stream/events` access, and `/assets/logo-c3ebba12.svg` or `/assets/logo-c3ebba12.svg`, etc., are still Links in `index-da1e4087.js` do not have root_url.

In addition, what is more serious is that when performing oauth2 authorization authentication, the link to jump is `/authorize` instead of `/ci/authorize`, and the link to jump after authorization is not `/ci` but `/`

2023-06-02 07:48 UTC, Seryta commented
> 

I'm using gitea, and the authorization jump link is indeed `example.com/ci/authorize`, but it doesn't work, I'm not sure where the problem is

2023-06-02 13:36 UTC, Seryta commented
> @Seryta Can you please check again with the latest commit. I tried to fix both streaming and redirecting, not sure if I found everything though.

@qwerty287 It's great, but there are still some problems with some pages. First, the login access is still `/authorize` instead of `/ci/authorize`, and secondly, `/assets` still has no root_path after logging in.

![image](https://github.com/woodpecker-ci/woodpecker/assets/31036794/2b32b145-6417-4f90-842b-6a798981bfe4)

2023-06-02 13:44 UTC, Seryta commented
After manually modifying the url to access `/ci/authorize`, there is no problem with the link that jumps back after the authorization is successful.

2023-06-03 12:45 UTC, Seryta requested changes

2023-06-03 12:45 UTC, Seryta commented on server/router/router.go
> +	"net/url"
please delete it, "net/url" imported and not used

2023-06-03 12:45 UTC, Seryta commented on server/web/web.go
> -	rootURL, _ := url.Parse(server.Config.Server.RootURL)
please remove "net/url"

2023-06-05 01:50 UTC, liyimeng commented
@qwerty287 shall we squash the commits into a single one? it is kind of messy

2023-06-05 01:50 UTC, Seryta commented
> @Seryta I looked again for usages without root path, can you try again with the latest commit? I'm really sorry to bother you for testing this.

Sorry, I just saw it today, I tested it, and the problem mentioned above still exists.
1. Automatically access `/authorize` instead of `/ci/authorize` when logging in for authorization
2. After manually accessing `/ci/authorize`, there is a problem with accessing the following links:
+ https://example.com/ci/assets/logo.svg?url, 404
+ https://example.com/assets/Repos-2587f056.js, 404
+ https://example.com/assets/ListItem.vue_vue_type_script_setup_true_lang-dc8e4876.js, 404
+ https://example.com/assets/Scaffold.vue_vue_type_script_setup_true_lang-4e0e2911.js, 404
+ https://example.com/assets/FluidContainer.vue_vue_type_script_setup_true_lang-df900462.js, 404
+ https://example.com/assets/useRepoSearch-2903cf6a.js, 404

2023-06-05 04:33 UTC, 6543 commented
@liyimeng pulls are squash-merged anyway ...

2023-06-05 06:35 UTC, liyimeng commented
> @liyimeng pulls are squash-merged anyway ...

do you mean it will squashed at merge automatically, cool !

2023-06-05 20:09 UTC, lafriks commented
For fronted part that needs to support subpaths I compile in vite with base path `<BASE_PATH>` and than on app startup replace it with configured value in all static files.

2023-06-10 20:52 UTC, 6543 requested changes
logo is broken if WOODPECKER_ROOT_PATH=""

2023-06-10 20:53 UTC, 6543 commented
html:
```
<img class="w-48 h-48" src="../assets/logo.svg?url">
```

2023-06-23 23:15 UTC, 6543 commented
login screen is still a white page :/

2023-07-09 19:19 UTC, 6543 commented
just as an idea ... instead of this "catch-all" aproach ... what if we just introduce a "basePath" that is `""` by default ... and can be changed so it will reflect this automatically ... and on the UI site we can use relative paths instead of absulte ... that should solve it ?

2023-07-10 10:21 UTC, lafriks commented
> Unfortunately, this is not possible because of Vite's compiling system which assumes that you use a prefix that is set at compile time. I didn't see any option to change this.

Usually I use something like `{{BASEPATH}}` in vite and then either with shell script in nginx docker image or with go code if embedded in binary replace it with actual subpath or `/` on start in index.html and *.js/*.css files.

2023-07-24 12:05 UTC, xoxys commented
Unpopular opinion: Remove any support for subpath deployments, as this always leads to problems. What are the benefits? Nowadays you can get certificates for free, and subdomains are not charged for in most cases either.

2023-07-24 12:29 UTC, gmemstr commented
To counter that, I'm very eager to see this working because I personally use Tailscale Funnel to expose some services to the internet. Tailscale Funnel only exposes a single subdomain for a machine, and so everything has to be routed with subpaths. Other services I use handle this fine (e.g Gitea/Forgejo, n8n etc) and _not_ supporting it is how I ended up opting for Gitea Actions instead. I can guarantee you I'm not the only one in this sort of position (and heck, maybe it's just for aesthetic purposes, but regardless, I believe that is it something that should & can work).

2023-08-07 14:03 UTC, 6543 approved these changes

2023-08-07 14:05 UTC, merged