Support user secrets
woodpecker-ci/woodpecker pull request #2126
Opened 2023-08-07 07:59 UTC by qwerty287

Just like org secrets. Therefore, I added a column `org_id` to users which associates the user with an org, everything else is used from org secrets. If there isn't an org for the user yet, it is created which means that every user will have an org.

Closes #1739

2023-08-07 08:32 UTC, xoxys commented
Was removed in https://github.com/woodpecker-ci/woodpecker/pull/2087#discussion_r1282750711

2023-08-07 08:35 UTC, anbraten commented
> This mainly improves the UX by moving these settings to the user settings (where it's much easier to find them) and it's also possible to add secrets before you enabled any repo.

Ahh okay haven't noticed that it got removed again. Could we simply add a link from the user settings page to the own org settings? At least we should have the settings icon on the orgs repo list again linking somewhere to change the secrets as well.

2023-08-07 08:41 UTC, anbraten commented
> Can't this settings icon just link to the user settings (`/user`)?

Yes

2023-08-07 20:41 UTC, 6543 requested changes

2023-08-07 20:41 UTC, 6543 commented on server/store/datastore/migration/022_add_org_id.go
> +			if err := sess.DropTable("orgs"); err != nil {
that would create problems!

2023-08-21 11:37 UTC, anbraten approved these changes

2023-08-21 13:04 UTC, merged