Revert breaking pipeline changes
woodpecker-ci/woodpecker pull request #2677
Opened 2023-10-31 12:28 UTC by qwerty287

Revert #2180 and #2480 so we can release v2.0 without breaking changes in pipeline config.

After merging #2476 we should apply these changes to a new v2.

After merging this, we should be ready for the 2.0 release.

2023-10-31 12:33 UTC, pat-s commented
> After merging https://github.com/woodpecker-ci/woodpecker/pull/2476 we should apply these changes to a new v2.

You mean v3?

---

I would also be ok with waiting a few days if you think #2476 can make it in and we're good to go then. I can't judge its status...

2023-10-31 12:36 UTC, 6543 requested changes
I'm against it ... as it was deprecated last release already ...

2023-10-31 13:55 UTC, anbraten commented
> Yes, and it's still deprecated (olds are used only as fallback). However, I'd make this only breaking in a new pipeline config version after we merged https://github.com/woodpecker-ci/woodpecker/pull/2476 .

I am also for leaving the fallback in for now. Biggest issue as mentioned before is that server admins are not enforced to tell their users to update their configs and users might not read migration notes. That's why I would like to get #1572 in to show warnings to the user if the pipeline contains deprecated parts.

2023-11-02 07:20 UTC, anbraten reviewed
We need to undo the changes in the yaml schema as well

2023-11-02 07:22 UTC, anbraten commented on pipeline/frontend/yaml/types/workflow.go
> +		PipelineDontUseIt ContainerList `yaml:"pipeline,omitempty"` // TODO: remove after v1.1.x version
```suggestion
		// Deprecated
		PlatformDontUseIt string `yaml:"platform,omitempty"` // TODO: remove in next major version
		// Deprecated
		BranchesDontUseIt *constraint.List `yaml:"branches,omitempty"` // TODO: remove in next major version
		// Deprecated
		PipelineDontUseIt ContainerList `yaml:"pipeline,omitempty"` // TODO: remove in next major version
```

2023-11-02 09:28 UTC, anbraten commented
> @anbraten the schema was never updated so it should still work

Ahh great 😅

2023-11-02 09:28 UTC, anbraten approved these changes

2023-11-02 14:01 UTC, 6543 approved these changes
well I still want to get rid of it

2023-11-02 14:02 UTC, anbraten commented
> well I still want to get rid of it

Sure, next release to do so will come 😉

2023-11-02 14:31 UTC, merged