Replace `interface{}` with `any`
woodpecker-ci/woodpecker pull request #2807
Opened 2023-11-11 13:07 UTC by qwerty287

like golang: https://github.com/golang/go/commit/2580d0e08d5e9f979b943758d3c49877fb2324cb

2023-11-11 18:25 UTC, anbraten approved these changes

2023-11-11 20:32 UTC, 6543 commented on pipeline/rpc/proto/woodpecker.pb.go
> -var file_woodpecker_proto_goTypes = []interface{}{
dont touch generated files

2023-11-11 20:32 UTC, 6543 commented on pipeline/rpc/proto/woodpecker_grpc.pb.go
> +func _Woodpecker_Version_Handler(srv any, ctx context.Context, dec func(any) error, interceptor grpc.UnaryServerInterceptor) (any, error) {
same

2023-11-11 20:33 UTC, 6543 commented on server/store/mocks/store.go
>  func (_m *Store) CreatePipeline(_a0 *model.Pipeline, _a1 ...*model.Step) error {
same

2023-11-11 20:33 UTC, 6543 requested changes
as comments

2023-11-11 21:52 UTC, lafriks approved these changes

2023-11-12 17:23 UTC, 6543 approved these changes

2023-11-12 17:23 UTC, merged