Ignore pipelines without config
woodpecker-ci/woodpecker pull request #2949
Opened 2023-12-14 09:59 UTC by anbraten

closes #2312

2023-12-14 09:59 UTC, anbraten commented
Haven't tested it yet

2023-12-14 18:32 UTC, 6543 commented
yes the forge implementations have to report if its realy a 404 or something else :D

2023-12-19 02:27 UTC, 6543 requested changes

2023-12-19 02:27 UTC, 6543 commented on server/forge/configFetcher.go
> +func (m *ErrConfigNotFound) Error() string {
should implement errors.Is interface

2023-12-19 02:27 UTC, 6543 commented on server/forge/configFetcher.go
> +type ErrConfigNotFound struct {
move error to `server/forge/types/errors.go`

2023-12-19 02:27 UTC, 6543 commented on server/forge/configFetcher.go
> +	return nil, &ErrConfigNotFound{configs: configs}
the forge drivers should report back if it's a 404 or something else

2023-12-21 00:04 UTC, 6543 approved these changes

2023-12-21 00:05 UTC, 6543 commented
request another review as changed by me

2023-12-21 00:06 UTC, 6543 commented
@anbraten you might also code comment if you found something

2023-12-21 08:09 UTC, xoxys commented on server/pipeline/create.go
> +	pipelineErrors "go.woodpecker-ci.org/woodpecker/v2/pipeline/errors"
We use already `pipeline_errors` in multiple other locations? Would you prefer `pipelineErrors`?

2023-12-21 08:09 UTC, xoxys commented on server/pipeline/create.go
> +	forgeTypes "go.woodpecker-ci.org/woodpecker/v2/server/forge/types"
Same here, we use `forge_types` already.

2023-12-21 10:12 UTC, xoxys approved these changes

2023-12-21 10:13 UTC, merged