Support custom steps entrypoint
woodpecker-ci/woodpecker pull request #2985
Opened 2023-12-21 17:03 UTC by qwerty287

Closes https://github.com/woodpecker-ci/woodpecker/issues/278

2023-12-21 19:32 UTC, 6543 requested changes
It was deliberatly removed because of security concerns.

If added there need some other checks made too

2023-12-22 15:37 UTC, zc-devs commented on pipeline/backend/kubernetes/pod_test.go
> +		[]string{"go get", "go test"}, []string{"woodpecker-cache:/woodpecker/src/cache"}, []string{"cloudflare:1.1.1.1"}, nil,
In this test an entrypoint should be tested. Set some example value.

2023-12-22 20:33 UTC, 6543 commented
plugins should not count as plugins anymore if the entrypoint ha schanged

2023-12-22 20:35 UTC, 6543 commented
and the pull title is missleding, when i was reading it, i thought "oh woodpecker server gets an custom endpoint?!?" - well if you read carefull you might get it.

why not put "steps" upfront?

2023-12-23 07:30 UTC, 6543 commented
:point_up: yes that title is nide :heart:  - beside the pull needs conflict resolve :sweat:

2023-12-24 08:28 UTC, anbraten commented on docs/docs/20-usage/20-workflow-syntax.md
> +Allows you to specify the entrypoint for Docker and Kubernetes. Note that this must include the full command as list, including arguments (e.g. `["/bin/sh", "-c"]`).
```suggestion
Allows you to specify the entrypoint for containers. Note that this must be a list of the command and its arguments (e.g. `["/bin/sh", "-c"]`).
```

2023-12-24 08:28 UTC, anbraten commented on pipeline/backend/kubernetes/pod.go
> +			command = entrypoint
What happens to the arguments?

2023-12-24 08:28 UTC, anbraten commented on pipeline/backend/local/local.go
> +	// TODO use `entrypoint` from yaml
Was at the beginning a bit confused which yaml you refer to 😅 

```suggestion
	// TODO support `entrypoint` from pipeline config
```

2024-01-10 02:38 UTC, 6543 commented on pipeline/frontend/yaml/types/container.go
> +	return len(c.Commands) == 0 && len(c.Entrypoint) == 0
can we have a test for this?

2024-01-18 22:01 UTC, 6543 approved these changes

2024-01-19 04:34 UTC, merged