Fixed IPv6 host aliases
woodpecker-ci/woodpecker pull request #2992
Opened 2023-12-22 20:11 UTC by zc-devs

Closes #2991

2023-12-22 20:39 UTC, lafriks commented on pipeline/frontend/yaml/compiler/convert.go
> +		splitArr := strings.SplitN(extraHost, ":", 2)
strings.Cut should be used instead

2023-12-22 20:53 UTC, 6543 commented on pipeline/frontend/yaml/compiler/convert.go
> +		extraHosts = append(extraHosts, extraHost)
```suggestion
		extraHosts = append(extraHosts, backend_types.HostAlias{
			Name: name,
			IP:   ip,
		})
```

2023-12-22 20:59 UTC, 6543 approved these changes

2023-12-22 21:17 UTC, 6543 commented on pipeline/frontend/yaml/compiler/convert.go
> +	extraHosts := []backend_types.HostAlias{}
```suggestion
	var extraHosts []backend_types.HostAlias
```

2023-12-22 22:16 UTC, lafriks requested changes

2023-12-22 22:16 UTC, lafriks commented on pipeline/frontend/yaml/compiler/convert.go
> +	var extraHosts []backend_types.HostAlias
As the resulting array length is known it is better to initialize it either with enough capacity or with needed length initialy:
extraHosts := make([]..., len(container.ExtraHosts))

And the assign values already by loop index

2023-12-22 23:18 UTC, lafriks commented on pipeline/frontend/yaml/compiler/convert.go
> +	extraHosts := make([]backend_types.HostAlias, 0, len(container.ExtraHosts))
```suggestion
	extraHosts := make([]backend_types.HostAlias, len(container.ExtraHosts))
```

And then just extraHosts[i].Name = name and same for IP

This way array objects will be allocated at once thus making it more optimal

2023-12-22 23:29 UTC, 6543 commented
also added dedicated error :)

2023-12-22 23:31 UTC, lafriks approved these changes

2023-12-22 23:42 UTC, merged

2023-12-23 14:36 UTC, zc-devs commented
Thank you, guys!