Remove prefix from services
woodpecker-ci/woodpecker pull request #3079
Opened 2023-12-30 11:36 UTC by qwerty287

supersedes https://github.com/woodpecker-ci/woodpecker/pull/1960

2023-12-30 12:38 UTC, anbraten approved these changes

2023-12-30 13:26 UTC, 6543 commented
i wonder where we get the collision :/

2023-12-30 13:27 UTC, 6543 requested changes
prevent accidental merge

2024-01-09 17:36 UTC, 6543 approved these changes

2024-01-09 17:56 UTC, merged