Lint for event filter and deprecate `exclude`
woodpecker-ci/woodpecker pull request #3222
Opened 2024-01-19 16:13 UTC by qwerty287

Closes https://github.com/woodpecker-ci/woodpecker/discussions/2174

- return bad habit error if no event filter is set
- If this is applied, it's useless to allow `exclude`s on events. Therefore, deprecate it together with `include`s which should be replaced by `base.StringOrSlice` later.

2024-01-19 16:48 UTC, 6543 requested changes
let me have a look into the discussion first ...

... as i told - discussions are a bad "representation" i normaly dont get either a notice nore the current consensus from it

2024-01-19 17:02 UTC, anbraten commented on pipeline/errors/error.go
> +	PipelineErrorTypeBadHabit    PipelineErrorType = "bad_habit"   // some generic error
```suggestion
	PipelineErrorTypeBadHabit    PipelineErrorType = "bad_habit"   // some bad-habit error
```

2024-02-08 09:17 UTC, anbraten approved these changes

2024-02-08 09:17 UTC, anbraten commented on docs/docs/91-migrations.md
> +- Deprecated `includes` and `excludes` support from event filter
We might directly remove it from the available docs as well, so no one will start using it.

2024-02-08 09:17 UTC, anbraten commented
@6543 Did you had the chance to read the discussion?

2024-02-08 16:09 UTC, 6543 commented
Not realy ... and i dont get why we should remove exclude?

2024-02-08 16:18 UTC, 6543 commented
Thanks github ... i had a detailed text. I recap it in a tldr now: 

When filter currently has AND, OR and NAND, to build all combinations.

removing exclude is removing NAND

There is a workaround: use eval; but we should not encurage long eval statements if the simple filters just work fine

2024-02-08 16:19 UTC, 6543 requested changes
PS: mentioned dicsuccion does not argue at all why exclude justd be removed!

2024-02-08 16:33 UTC, 6543 commented
Ah ok ... well i do use it ... looks like i have to migrate on repo.

Only for events is fine but the codecomment do not indicate that

2024-02-10 10:52 UTC, 6543 commented on docs/docs/91-migrations.md
> +- Deprecated `includes` and `excludes` support from event filter
```suggestion
- Deprecated `includes` and `excludes` support from **event** filter
```

2024-02-10 10:54 UTC, 6543 commented on pipeline/frontend/yaml/linter/linter.go
> +					Docs:  "https://woodpecker-ci.org/docs/next/usage/workflow-syntax#event-1",
```suggestion
					Docs:  "https://woodpecker-ci.org/docs/usage/workflow-syntax#event-1",
```

2024-02-10 10:55 UTC, 6543 commented on pipeline/frontend/yaml/linter/linter.go
> +						Docs:  "https://woodpecker-ci.org/docs/next/usage/workflow-syntax#event",
```suggestion
						Docs:  "https://woodpecker-ci.org/docs/usage/workflow-syntax#event",
```

2024-02-10 11:00 UTC, 6543 commented on pipeline/frontend/yaml/linter/linter_test.go
> +			want: "Please set an event filter",
why does it suggest an event filter if global does already have it?

2024-02-10 11:05 UTC, 6543 commented
fixed the "code comment" issue ...
... I only found one issue left - but it's a minor thing and if it's hard to fix it now we can let it open for later

2024-02-10 16:31 UTC, 6543 commented on pipeline/frontend/yaml/linter/linter_test.go
> +			want: "Please set an event filter",
Well i guess, user having questions abour that message or not will finaly tell us

2024-02-10 16:32 UTC, 6543 approved these changes

2024-02-10 16:33 UTC, merged