Deprecate `detached`
woodpecker-ci/woodpecker pull request #3408
Opened 2024-02-18 19:04 UTC by qwerty287

solves todo point in https://github.com/woodpecker-ci/woodpecker/discussions/2170#discussioncomment-7047394

2024-02-19 00:07 UTC, lafriks approved these changes

2024-02-19 07:30 UTC, anbraten approved these changes

2024-02-19 07:30 UTC, anbraten commented on pipeline/frontend/yaml/types/container.go
> +		// Deprecated TODO remove in 3.x
```suggestion
		// TODO Deprecated, remove in 3.x
```

2024-02-20 10:05 UTC, 6543 requested changes
I'm against deprecating it until we have a replacement for it

2024-03-29 08:44 UTC, closed without merging