Add `needs` for services and deprecate `detached`
woodpecker-ci/woodpecker pull request #3411
Opened 2024-02-19 08:33 UTC by qwerty287

related to #2495

Treat services just like steps to support `depends_on` (including all directions: step -> service, step -> step, service -> service, service -> step)

2024-02-20 10:08 UTC, 6543 commented
it does not solve the thing detatched was able to and is now supposed to remove :/

I still if following the KISS principe detatched is the best way to do so.

yes the proposed feature here would have other benefits through ;)

PS: if service is not registered at a single step -> always run; else only if step is also exec ...

2024-06-27 12:24 UTC, 6543 requested changes
I'm still against it!

as long as we have no way to run something that first has to be build as service.

we can do so if services can access the workspace too and also can depend on steps ...

... but we have to implement it first

2024-06-27 12:31 UTC, 6543 commented
in exactly this way: https://github.com/woodpecker-ci/woodpecker/issues/2495#issuecomment-2194557622 ?

as far as i remember the backend engine do not do that exactly this way ...

2024-06-27 12:33 UTC, 6543 commented on pipeline/frontend/yaml/compiler/convert.go
> +	if container.Detached {
until we dont have detatched removed from the frontend we should not remove that!!

else a user can create two services with the same hostname

2024-06-27 12:34 UTC, 6543 commented on pipeline/frontend/yaml/types/container.go
> +		Detached  bool               `yaml:"detach,omitempty"`
you want to depricated directory and name too ?!?

2024-06-27 12:36 UTC, 6543 commented
be aware that steps now can have the same name and its not that uncommon to have a service and a step called the same

2024-06-27 15:25 UTC, 6543 commented on pipeline/frontend/yaml/types/container.go
> +		Detached  bool               `yaml:"detach,omitempty"`
yes so you should move it form the main list below

2024-06-27 15:26 UTC, 6543 commented
> Yes having both step/service with the same name could be possible but this has caused so many problem already...

well no we fixed all of them and now the code works better!!!

the (pipeline-)backend should not care about the name at all as long as it is no service!

2024-07-18 17:05 UTC, 6543 commented
why not add a new keyword specific to services: `needs`  so we don't have any collision

2024-09-05 12:55 UTC, 6543 commented on pipeline/frontend/yaml/compiler/convert.go
> +	if container.Detached {
well i have a solution: prefix the step name with the uuid ... this way you can not guess the hostname (as it was with non service-steps that are detached) and they cant clash

2024-09-05 12:56 UTC, 6543 commented on pipeline/frontend/yaml/compiler/convert.go
> +	if stepType != backend_types.StepTypeService {
good question ... I would pass them down if they exist ... but we can address that in a new pull that also alters the json schema and docs

2024-09-08 00:21 UTC, 6543 commented
asap https://github.com/woodpecker-ci/woodpecker/pull/3411#discussion_r1745488047 this is addressed It  looks realy good.

I just want to make use one usecase works:

if a service is defined but non of the steps need it (ignoring all when filters) it runs as the current modell all the time and starts before all steps ...

2024-09-14 13:33 UTC, 6543 commented
Yep that should fix it :)

2024-09-17 10:42 UTC, 6543 commented on docs/docs/20-usage/60-services.md
> +You can use any step property, including `depends_on`. Services can depend on other services and steps.
Still up to date?

2024-09-27 23:02 UTC, 6543 commented
Thanks for resolving ... i realy do have to make miselfe time to properly review it 😓

2024-10-02 11:44 UTC, 6543 commented
added two TODOs ...

I'll have a look in addressing them and streamline the code to better to maintain.
Also i will create more test coverage and try to cover the edgecases

## TODO:
- [ ] make generic service (currently how services work) work
- [ ] explizite document how services work
- [ ] document what can depend upon what
- [ ] document what can need upon what
- [ ] more tests
- [ ] better maintainable code (with look into using an dag in the backend) (might be done before merging this or at least prepare here)
- [ ] create generic DAG type we can use
- [ ] allow need on sequential steps

2024-10-02 11:45 UTC, 6543 commented
I'll created an todo list, feel free to start addressing them ... else I'll catch them on one by one ...

If it's easyer for you i can create pull requests onto your feature branch, so just tell me, else I'll push short commits

2024-11-15 08:53 UTC, zc-devs commented on docs/docs/20-usage/20-workflow-syntax.md
> +Just like [`depends_on`](#depends_on), but for services.
Why new keyword? Why not `depends_on`?

2024-11-15 19:29 UTC, zc-devs commented on docs/docs/20-usage/20-workflow-syntax.md
> +Just like [`depends_on`](#depends_on), but for services.
What is the probability, that a service (noun like postgres, mongo) would have name like a step (verb like prepare, build, test, build-image, push-image)? And in those rare cases, when they do, we can throw error like `ambigous names in depends_on, rename step or service`.
If this is the only reason, I propose to use only `depends_on`.

2024-11-16 09:05 UTC, zc-devs commented on docs/docs/20-usage/20-workflow-syntax.md
> +Just like [`depends_on`](#depends_on), but for services.
Clean your pipeline: rename steps to `test-mysql`, `test-postgres` or (`unit-test`, `build`) `integration-test-sqlite`, `integration-test-mysql`, `integration-test-postgres`. No need in different keyword.
Let me ask some questions: what is the behavior, if I define multiple steps with the same name? What if I define multiple services with the same name? Apply this behavior to inter-group naming.
If I can make both of them with the same names _and_ you do not want throwing error on the same names when `depends_on` is used, alright - do not fail, but depend on all of them. Except on step itself, which defines `depends_on`, obviously. Again, no need in separate keyword, IMO.

2024-11-26 21:49 UTC, pat-s commented
Given the open discussions and todos, I'll remove this from the 3.0 milestone.

2025-01-02 16:20 UTC, closed without merging

2025-01-03 00:12 UTC, lafriks commented
Damn, I was waiting for this 🙃