Create devcontainer.json
woodpecker-ci/woodpecker pull request #3698
Opened 2024-05-12 23:34 UTC by StemmlerSisters

2024-05-13 17:22 UTC, 6543 commented
links to some documentation would also be useful

2024-05-14 18:32 UTC, lafriks requested changes

2024-05-14 18:32 UTC, lafriks commented on .devcontainer/devcontainer.json
> +  "image": "mcr.microsoft.com/devcontainers/universal:2",
I would prefer we would use `mcr.microsoft.com/devcontainers/go:1.22-bullseye` with features required for woodpecker development like `ghcr.io/devcontainers/features/node:1` with same node version we use in pipelines etc

2024-05-14 20:36 UTC, lafriks commented
> Hello! Could you explain why this change is necessary and what it's doing?

This would allow developing woodpecker without needing to install development tools (go, node etc) on your pc, VSCode would detect and ask to switch to devcontainer mode where it starts vscode instance in container that is build based on this file.

More info in <https://containers.dev/>

Would be nice so that would also allow setting up test gitea instance etc to work with but this is not prerequesite for this PR

2024-05-14 22:11 UTC, anbraten commented
> Would be nice so that would also allow setting up test gitea instance etc to work with but this is not prerequesite for this PR

Would be great to have the same setup as we use for gitpod. Shouldn't be actually to tough to achieve using devcontainers with a docker-compose file.

2024-05-14 23:04 UTC, 6543 commented
can containers use nix flakes?

if so, we can use the flake to maintain the dependencys

2024-05-15 09:57 UTC, lafriks commented
> Do we really need yet another dev environment? We just had that discussion in #3702.

devcontainers are supported out of the box in vscode (github codespaces and other services also use it), it has more compatibility between different tools not like gitpod or nix that works only with specific environment

devcontainers can be used in win/linux/mac and does not depend on any external service like gitpod

2024-05-15 12:00 UTC, lafriks commented
Personally I don't use gitpod as I don't see any reason for me to use it (it's external commercial cloud, requires special plugin and registration etc).

Devcontainers can be used in GitHub to do quick development and contributions thus more easy to use:
![image](https://github.com/woodpecker-ci/woodpecker/assets/165205/ac4cacca-c772-45a9-95e7-e5b86e14ded0)

VSCode does not require any external services at all (just VSCode and Docker), have not used but I think IntelliJ also supports devcontainers out of the box.

There are also multiple open source tools that allow to use devcontainers having just docker and this tool installed (ex [daytona.io](https://www.daytona.io/) or [devpod.sh](https://devpod.sh/) )

Nix is nice but also requires to have nix/nixos and works only for linux but it's small config so not that it's hard to maintain.

So I would vote for droping gitpod and replacing it with devcontainers

2024-05-16 20:03 UTC, 6543 commented
Well we can move forwarx with this and remove you custom made 'in_docker' makefile target https://github.com/woodpecker-ci/woodpecker/blob/402e357fe8754067a91c958e1b819d13b9faf6a1/Makefile#L44

Also the related dockerfile to build the dev env can be used here for this ...

2024-05-16 20:04 UTC, 6543 commented
and we could reuse nix: https://github.com/xtruder/nix-devcontainer

2024-05-17 13:57 UTC, lafriks commented
> and we could reuse nix: https://github.com/xtruder/nix-devcontainer

does not look very standard way to use devcontainers and not sure it works in github codespaces

2024-05-20 13:16 UTC, 6543 commented
Well it either works or the devcontaiberprommise is broken

2024-05-20 14:01 UTC, lafriks commented
in cloud based environments there could be some problems with specific used mounts/volumes and security options used there

2024-05-20 14:34 UTC, 6543 commented
I'll make a test :)

2024-05-20 14:41 UTC, anbraten commented
Started some testing here: https://github.com/woodpecker-ci/woodpecker/compare/main...anbraten:woodpecker:dev-container Mainly missing the env var setup

2024-05-24 12:49 UTC, closed without merging