Split repo trusted setting
woodpecker-ci/woodpecker pull request #4025
Opened 2024-08-11 09:30 UTC by qwerty287

related to https://github.com/woodpecker-ci/woodpecker/discussions/3758

2024-08-19 08:58 UTC, zc-devs reviewed
> get it into 3.0

2024-08-19 08:58 UTC, zc-devs commented on server/store/datastore/migration/035_split_trusted.go
> +		if err := renameColumn(sess, "repos", "trusted_conf", "trusted"); err != nil {
`trusted` column has been deleted at 61 line. Maybe this is not necessary.

2024-08-30 07:42 UTC, anbraten commented
I am not really a fan of this split. Although I kinda see the general idea behind it, it complicates the CI (not really interested to move towards Jenkins and similar tools) and it shifts the security guidelines from the agent admin to the repo admin. Therefore multiple agents aren't able to provide different settings.

2024-09-05 11:11 UTC, 6543 approved these changes

2024-09-05 12:50 UTC, 6543 requested changes
migration fail related !!!

https://ci.woodpecker-ci.org/repos/3780/pipeline/20192/36

2024-09-06 05:47 UTC, anbraten requested changes
Not confined by the benefit of splitting the setting.

2024-09-06 05:55 UTC, anbraten commented
> Repo admins can't change this setting if they're not a server admin and usually the server admin is also the agent admin I think.

Isn't that the reason why this is currently an agent config (at least for the kubernetes options). It would only make sense for smaller deployments where server admins are agent admins as well I guess. For larger teams / orgs with or when supporting #267 those options would be quite unimportant.

2024-09-06 10:27 UTC, zc-devs commented
> this is currently an agent config (at least for the kubernetes options)
Where?

> this issue is not different from how it works now. Enabling trusted is currently also on repo-level and this PR does not give any way to get more privileges than before

2024-09-06 15:15 UTC, zc-devs commented
> You mean the "feature gates"?

I was asking. @anbraten, what did you mean by `agent config`? Could you provide an example?

Agent's feature gates != settings per a repo.

> having it on a repo level additionally can still be helpful as you might have repos that shouldn't be able to use some features

--- 

> it complicates the CI

The same way as `trusted` does.

> not really interested to move towards Jenkins and similar tools

Could you elaborate?

> it shifts the security guidelines from the agent admin to the repo admin

To the server/instance admin, if I understand correctly. The same as `trusted`. And doesn't shift, but adds per repo settings.

2024-09-07 13:26 UTC, zc-devs commented
Maybe using [ALTER TABLE DROP COLUMN](https://www.sqlite.org/lang_altertable.html) will help.
`server/store/datastore/migration/common.go:dropTableColumns(...)`

2024-09-08 13:17 UTC, zc-devs commented
[Using_official_DROP_COLUMN_syntax.patch](https://github.com/user-attachments/files/16922333/Using_official_DROP_COLUMN_syntax.patch) works for me on your branch
```
root@4296e32370b1:/src/woodpecker# make test-server-datastore-coverage
go test -race -cover -coverprofile datastore-coverage.out -timeout 300s -tags 'test ' go.woodpecker-ci.org/woodpecker/v2/server/store/...
        go.woodpecker-ci.org/woodpecker/v2/server/store         coverage: 0.0% of statements
?       go.woodpecker-ci.org/woodpecker/v2/server/store/types   [no test files]
        go.woodpecker-ci.org/woodpecker/v2/server/store/mocks           coverage: 0.0% of statements
ok      go.woodpecker-ci.org/woodpecker/v2/server/store/datastore       2.236s  coverage: 72.3% of statements
ok      go.woodpecker-ci.org/woodpecker/v2/server/store/datastore/migration     48.395s coverage: 58.8% of statements
root@4296e32370b1:/src/woodpecker#
```

2024-09-15 12:47 UTC, 6543 commented
> Maybe using [ALTER TABLE DROP COLUMN](https://www.sqlite.org/lang_altertable.html) will help. `server/store/datastore/migration/common.go:dropTableColumns(...)`
> 
> Offtop: I thought, ORM/migration tool should do this magic. Seems, I was wrong :)

ORM dont just drop data ... you have to specify that

2024-09-15 12:50 UTC, 6543 commented
As for the current structure I'm quite happy as it works (some strings atached...) but to cover the concerns ... an agent admin should be able to optionally overwrite security related things set by the server, if veasable like e.g. deny to mount volumes pointing to non docker volumes e.g. to the host ... 

But that has to be a backemd option as each backend has different security considderations

2024-09-15 14:04 UTC, 6543 commented on server/store/datastore/migration/022_add_orgs.go
> +		if err := sess.Sync(new(model.Org), new(syncRepo022), new(userV031), new(oldSecret022)); err != nil {
Unrelated?

2024-09-15 14:06 UTC, 6543 commented on server/store/datastore/migration/036_split_trusted.go
> +		for _, r := range repos {
You dont have to itterate in codd, let it do the database ...


Where(trusted).Col(x).Update(newModel(datafornew col))

2024-09-15 14:07 UTC, 6543 commented on server/store/datastore/migration/common.go
> +			return fmt.Errorf("table `%s`, drop columns %v: %w", tableName, columnNames, err)
Unrelated?

2024-09-30 10:10 UTC, 6543 commented on pipeline/frontend/yaml/linter/linter_test.go
> +
```suggestion
```
?

2024-09-30 10:13 UTC, 6543 commented on cli/exec/flags.go
> +		Usage:   "Set the metadata environment variable \"CI_REPO_TRUSTED_SECURITY\".",
```suggestion
		Sources: cli.EnvVars("CI_REPO_TRUSTED_NETWORK"),
		Name:    "repo-trusted-network",
		Usage:   "Set the metadata environment variable \"CI_REPO_TRUSTED_NETWORK\".",
	},
	&cli.BoolFlag{
		Sources: cli.EnvVars("CI_REPO_TRUSTED_VOLUMES"),
		Name:    "repo-trusted-volumes",
		Usage:   "Set the metadata environment variable \"CI_REPO_TRUSTED_VOLUMES\".",
	},
	&cli.BoolFlag{
		Sources: cli.EnvVars("CI_REPO_TRUSTED_SECURITY"),
		Name:    "repo-trusted-security",
		Usage:   "Set the metadata environment variable \"CI_REPO_TRUSTED_SECURITY\".",
```

2024-09-30 10:13 UTC, 6543 commented on cli/exec/flags.go
> +	// TODO remove CI_REPO_TRUSTED in 4.x
```suggestion
```

2024-09-30 10:14 UTC, 6543 approved these changes

2024-10-30 06:38 UTC, anbraten commented
> @anbraten maybe we can just merge this now as it's ready and discuss the general approach again?

Still not really convinced how this would really help users and think it mainly ignores UX while complicating existing options. Especially as it doesn't consider org level agents. Anyways will trust you making this helpful at some point.

2024-10-30 15:50 UTC, 6543 commented on server/store/datastore/migration/017_split_trusted.go
> +		var repos []*repoV035
pagination is missing ...

2024-10-30 15:51 UTC, 6543 requested changes
migration ...

2024-11-01 10:40 UTC, 6543 approved these changes

2024-11-01 11:59 UTC, 6543 commented
@qwerty287 lint err

2024-11-01 20:37 UTC, merged

2025-02-21 18:54 UTC, igniscyan commented
> > @anbraten maybe we can just merge this now as it's ready and discuss the general approach again?
> 
> Still not really convinced how this would really help users and think it mainly ignores UX while complicating existing options. Especially as it doesn't consider org level agents. Anyways will trust you making this helpful at some point.

Am I understanding correctly that the VOLUME, NETWORK, and SECURITY flags were agent settings before rather than repo settings?