Added documentation of all server configuration options
woodpecker-ci/woodpecker pull request #666
Opened 2022-01-07 15:45 UTC by KN4CK3R

While setting up my instance I searched for an overview of all available configuration options but could not find any.

Please have a look at the items with `TODO`. I could not find any information for these items. Feel free to extend these.

2022-01-08 20:06 UTC, 6543 requested changes

2022-01-08 20:06 UTC, 6543 commented on docs/docs/30-administration/10-server-config.md
> +### `WOODPECKER_GITHUB_CONTEXT`
will be deleted

2022-01-08 20:06 UTC, 6543 commented on docs/docs/30-administration/10-server-config.md
> +### `WOODPECKER_GITEA_CONTEXT`
will be deleted

2022-01-17 18:52 UTC, 6543 commented
update?

2022-02-03 18:31 UTC, anbraten commented
@6543 I update the options a bit to match the newly added and removed flags. Two things I noticed:
- Should we move the configs for the SCMs to their appropiate pages and just link to them at the end of this docs page, so we prevent duplicates?
- I would like to leave out documentation for some settings at the moment which are probably going to need a refactor in the next versions as documenting things will more likely direct users into using those settings which could lead to more migration problems in the case we deprecate those settings. Currently those are:

```yml
# all of those settings are quite close to the docker backend, but by adding new backend 
# like podman and kubernetes we probably have to think about more generic options for them or need to 
# rename them to something like WOODPECKER_DOCKER_...
WOODPECKER_VOLUME
WOODPECKER_DOCKER_CONFIG
WOODPECKER_ENVIRONMENT
WOODPECKER_NETWORK

# I am personally quite unsure how to use these endpoints and if they are really a approach we
# should keep or which should better be redesigned
WOODPECKER_SECRET_ENDPOINT
WOODPECKER_REGISTRY_ENDPOINT
WOODPECKER_GATEKEEPER_ENDPOINT
```

2022-02-03 20:51 UTC, KN4CK3R commented
Should we keep the documentation description with the one in the code? In this case we could generate parts of the documentation.

2022-02-06 20:04 UTC, 6543 approved these changes

2022-02-06 20:21 UTC, merged