Added documentation of all agent configuration options
woodpecker-ci/woodpecker pull request #667
Opened 2022-01-07 15:45 UTC by KN4CK3R

While setting up my instance I searched for an overview of all available configuration options but could not find any.

Please have a look at the items with `TODO`. I could not find any information for these items. Feel free to extend these.

2022-01-07 17:31 UTC, anbraten commented on docs/docs/30-administration/11-agent-config.md
> +Example: TODO
I would not add it to the docs atm at all as it is will be changed in the next release anyways, so we don't have to deprecate it.

2022-01-08 19:32 UTC, anbraten commented on docs/docs/30-administration/11-agent-config.md
> +
```suggestion
```

2022-01-08 19:50 UTC, 6543 requested changes

2022-01-08 19:50 UTC, 6543 commented on docs/docs/30-administration/11-agent-config.md
> +Configures the Woodpecker server address.
```suggestion
Configures gRPC address of the server.
```

2022-01-08 19:50 UTC, 6543 commented on docs/docs/30-administration/11-agent-config.md
> +### `WOODPECKER_DEBUG`
is deprecated, use WOODPECKER_LOG_LEVEL instead

2022-01-08 19:50 UTC, 6543 commented on docs/docs/30-administration/11-agent-config.md
> +Restrict builds by platform conditions.
will be hidden in later versions and on compile time instead

2022-01-08 19:52 UTC, anbraten commented on docs/docs/30-administration/11-agent-config.md
> +
```suggestion
```

2022-01-08 19:52 UTC, anbraten commented on docs/docs/30-administration/11-agent-config.md
> +
```suggestion
```

2022-01-08 22:09 UTC, 6543 approved these changes

2022-01-08 22:22 UTC, merged