Changelog for v0.15.0-rc1
woodpecker-ci/woodpecker pull request #676
Opened 2022-01-08 22:56 UTC by 6543

as title

please make suggestions or push against to impruve

2022-01-08 22:57 UTC, 6543 commented on CHANGELOG.md
> +## [v0.15.0](https://github.com/woodpecker-ci/woodpecker/releases/tag/v0.15.0) - 2022-01-08
```suggestion
## [v0.15.0-rc1](https://github.com/woodpecker-ci/woodpecker/releases/tag/v0.15.0-rc1) - 2022-01-08
```

2022-01-11 17:28 UTC, jolheiser requested changes
Small nits

2022-01-11 17:28 UTC, jolheiser commented on CHANGELOG.md
> +  * Add linter bidichk to prevent malicios utf8 chars (#516)
```suggestion
  * Add linter bidichk to prevent malicious utf8 chars (#516)
```

2022-01-11 17:28 UTC, jolheiser commented on CHANGELOG.md
> +  * Remove "panic()" as much as posible from code (#682)
```suggestion
  * Remove "panic()" as much as possible from code (#682)
```

2022-01-11 17:28 UTC, jolheiser commented on CHANGELOG.md
> +  * Hide gin routes logging on none-debug starts (#603)
```suggestion
  * Hide gin routes logging on non-debug starts (#603)
```

2022-01-11 17:28 UTC, jolheiser commented on CHANGELOG.md
> +  * add search to docs (#448)
```suggestion
  * Add search to docs (#448)
```

2022-01-11 17:33 UTC, jolheiser approved these changes

2022-01-11 17:41 UTC, merged